Q5g:
	g++ D2Q5g.cpp -o D2Q5g.out && ./D2Q5g.out
	gnuplot D2Q5g.p
	
Q5:
	g++ D2Q5_v2.cpp -o D2Q5_v2.out && ./D2Q5_v2.out
	gnuplot D2Q5.p

Q9:
	g++ D2Q9_v2.cpp -o D2Q9_v2.out && ./D2Q9_v2.out
	gnuplot D2Q9.p
		
clean:
	rm -f *.out *.dat *.log
	clear
